import unittest

# # from tools.active_bits_iterable import Active_bits_iterable_Test
# # from tools.bytes_2_bit_iterative import Bytes_2_bit_iterative_Test
# # from tools.bytes_2_decimal_part import Bytes_2_decimal_part_Test
# # from tools.float_2_bytes import Float_2_bytes_Test

from tools.active_bits_Test import Active_bits_Test
from tools.binary_string_2_bytes_Test import Binary_string_2_bytes_Test
from tools.bytes_2_binary_string_Test import Bytes_2_binary_string_Test
from tools.bytes_2_bits_Test import Bytes_2_bits_Test
from tools.bytes_2_integer_Test import Bytes_2_integer_Test

from tools.compare_files_Test import Compare_Files_Tests
from tools.count_active_bits_Test import Count_active_bits_Test
from tools.count_inactive_bits_Test import Count_inactive_bits_Test
from tools.get_byte_Test import Get_byte_Test
from tools.integer_2_bytes_Test import Integer_2_bytes_Test

from tools.integer_2_string_Test import Integer_2_string_Test
from tools.read_bit_Test import Read_bit_Test
from tools.replace_byte_Test import Replace_byte_Test
from tools.rotate_on_left_4_bits_Test import Rotate_on_left_4_bits_Test
from tools.rotate_on_left_4_bytes_Test import Rotate_on_left_4_bytes_Test

from tools.rotate_on_right_4_bits_Test import Rotate_on_right_4_bits_Test
from tools.rotate_on_right_4_bytes_Test import Rotate_on_right_4_bytes_Test
from tools.xor_4_bytes_Test import XOR_4_bytes_Test

unittest.main()
